### ISSUE TITLE
Create an overview and outline page for the workshop

### ISSUE THREAD

**Issue by tracykteal** [Reproducible-Science-Curriculum/Reproducible-Science-Hackathon-Dec-09-2015#2]
Create an overview document of the workshop, that describes what the workshop is about and its goals, along with the curriculum and link to the materials.

Like for the Data Carpentry Genomics workshop
https://github.com/datacarpentry/genomics-workshop
but better, because that one still needs work too. 

This will help potential hosts and instructors better understand the workshop and its goals and implementation and how the modules can fit together.

**Comment by tracykteal** [comment]
This is being addressed by the repo @kcranston created https://github.com/Reproducible-Science-Curriculum/workshop-planning

**Comment by kcranston** [comment]
Yup. We have such a document now. Closing.
