### ISSUE TITLE
Git Lessons

### ISSUE THREAD

**Issue by iamciera** [Reproducible-Science-Curriculum/Reproducible-Science-Hackathon-Dec-09-2015#6]
Where are we on this? I was thinking I could work on it during the Hackathon. Did we decide that we wanted to have a git lesson in RStudio? I have been looking into it and there are pros and cons.  If yes, I could work on making one. I could also clean up/outline all the past Git lessons so that the instructor could choose between the different options for teaching git.  Outlining the pros and cons for each method would be helpful for instructors and students. We could maybe even start the Git lessons with the different options of learning/using git.

 Depending on time, the outlining could be expanded to other lessons as suggested by @tracykteal  [Issue 2: creating an overview for the course](https://github.com/Reproducible-Science-Curriculum/Reproducible-Science-Hackathon-Dec-09-2015/issues/2).

**Comment by hlapp** [comment]
That would be great to clean up and update! @kcranston wrote some updates for the Git lesson in prep for the DUML workshop in September. She would know where that's left.

A Git lesson in RStudio would have obvious advantages, and would I think well be able to get at some of the shortcomings of the web-only less that Karen wrote down after the DUML workshop. However, then this would become a language-specific module as well (and we would then therefore still need a Python-compatible version of it). Perhaps that's the price that needs to be paid to integrate it well into the rest.

**Comment by iamciera** [comment]
More detailed issues have been made in the issues section of the version control repo: https://github.com/Reproducible-Science-Curriculum/rr-version-control/issues.

**Comment by hlapp** [comment]
Here's a pointer to the `git2r` way of using Git within R that I was referring to earlier for a project that came out of a NESCent hackathon: https://gist.github.com/zkamvar/58be1b25798378a58aa9

**Comment by kcranston** [comment]
Closing this, since there are more specific issues on the version control repo.
