### ISSUE TITLE
Better exercise(s) to go with File Naming and Organization

### ISSUE THREAD

**Issue by kcranston** [Reproducible-Science-Curriculum/Reproducible-Science-Hackathon-Dec-09-2015#7]
The forensic exercise with this lesson is designed to motivate the lesson in advance of the slides. Based on feedback, the lesson would be more effective if we removed the pre-presentation exercise and added a new exercise that better demonstrated & used the best practices described in the slides.

**Comment by kcranston** [comment]
Brainstorming possibilities:
1. Provide a script that does some analysis or makes a plot. The script has blank variables (directory_name, slug, extension, etc). The exercise is to organize / rename files in a directory so that the script works.
2. Provide two directories with the same project but organized in different ways and have the students write pseudocode to do something. Discuss with partner which structure made the analysis easier, provide other suggestions for even better organization.

**Comment by iamciera** [comment]
## Notes from group disscussion
-   Write shell scripts? The script would be giving them the code. Do we want to forcus on machine readable. 
-   The two pieces to the module: Human readable and machine readable.
-   Automation section could go into machine sorting. While the organization section would focus more on R project set-up.
-   Give them links to other example projects, either in the repro or in Github. Then _they_ set-up a project. 
-   The entire organization lesson should take about an hour if not less.

Proposed Acitivity from Karen:
-   no exercise in the begining 
-   orgnaization and file naming (core concepts)
-   exercise (Human readablility activity)
-   slide deck optional detailed (more minor details)

**Comment by kcranston** [comment]
Heads up for @jennybc that we have a proposal for re-organizing this lesson, including a big shuffling of the two existing slide decks from 
1. organization and 
2. file naming 

to 
1. core concepts on organizating and naming
2. more details and examples on organization and naming

**Comment by jennybc** [comment]
All sounds good to me! I will keep my ears open for specific things I could help on, if you need it. Thanks for working on this!
